### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by limeburst** [limeburst/caduceus#6]
Let [PistonDevelopers/hematite](https://github.com/PistonDevelopers/hematite) use the name.

Candidates:

* [Fougèrite](https://en.wikipedia.org/wiki/Fougèrite)

**Comment by bvssvni** [comment]
I was thinking of Mercurial - moon, but it seems Mercury doesn't have any moons https://en.wikipedia.org/wiki/Hypothetical_moon_of_Mercury.

**Comment by limeburst** [comment]
> NASA jokingly proposed the name Caduceus, after the staff carried by the Roman god Mercury, during an April Fools' Day joke in which the MESSENGER spacecraft supposedly discovered a moon from Mercurial orbit.

Thank you for the suggestion, @bvssvni!
